[package]
name = "ao_hashmaps"
version = "0.1.0"
authors = ["David Konsumer <konsumer@jetboystudio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
